# Generated by Django 4.1.1 on 2022-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('language', models.CharField(choices=[('ru', 'RU'), ('en', 'EN')], default='RU', max_length=2, verbose_name='Язык')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='videos', to='videos.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('title',),
            },
        ),
    ]
