# Generated by Django 4.1.1 on 2022-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.category', verbose_name='Категории'),
        ),
    ]
