# Generated by Django 4.1.1 on 2022-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('description',),
            },
        ),
        migrations.AddField(
            model_name='video',
            name='github_link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на проект в GitHub'),
        ),
        migrations.AddField(
            model_name='video',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.link', verbose_name='Дополнительные ссылки'),
        ),
    ]
