# Generated by Django 4.1.1 on 2022-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_link_video_github_link_video_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='github_link',
        ),
        migrations.AddField(
            model_name='video',
            name='author_github_link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на проект автора в GitHub'),
        ),
        migrations.AddField(
            model_name='video',
            name='my_github_link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на мой проект в GitHub'),
        ),
    ]
