# Generated by Django 4.1.1 on 2022-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('videos', '0007_alter_video_difficult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AlterField(
            model_name='video',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='videos', to='links.link', verbose_name='Дополнительные ссылки'),
        ),
    ]
