# Generated by Django 4.1.1 on 2022-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
        ('videos', '0008_delete_link_alter_video_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos', to='tech.category', verbose_name='Категории'),
        ),
    ]
