# Generated by Django 4.1.1 on 2022-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
        ('links', '0002_alter_link_options_link_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('description',), 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RemoveField(
            model_name='link',
            name='category',
        ),
        migrations.AddField(
            model_name='link',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='links', to='tech.category', verbose_name='Категории'),
        ),
    ]
